apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scout-deployment
  name: scout-deployment
  namespace: joresp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: scout-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: scout-deployment
    spec:
      containers:
      - image: nginx:1.16.0
        name: nginx
        resources:
          limits:
            cpu: 0.5
            memory: 256Mi
          requests:
            cpu: 0.3
            memory: 64Mi  
